### ISSUE TITLE
Single jupyter notebook opens multiple instances of Slicer

### ISSUE THREAD

**Issue by marcmorcos** [Slicer/SlicerNotebooks#7]
Upon opening a Jupyter notebook (not code is executed yet) with the Slicer 5.0 kernel, two instances of 3D Slicer are opened.

When running code, a third 3D slicer instance is opened and this is the one that gets affected by the code.

Using 3D Slicer: 5.0.3

1-Is there a way to fix this?
2-On a related note, is there a way to run it headless and only render the views as requested. I can do the remote render per the notebook examples but would like to keep slicer hidden.

Thanks,
Marc

**Comment by lassoan** [comment]
Are you using VS Code? VS Code is highly opinionated about how a Jupyter kernel is supposed to work and its assumptions are often wrong.

> Upon opening a Jupyter notebook (not code is executed yet) with the Slicer 5.0 kernel, two instances of 3D Slicer are opened.

For some reason, VS Code starts these extra kernel instances. Probably most users don't even notice this, so it does not come up as a problem, and therefore there may not be an option to disable this.

> is there a way to run it headless and only render the views as requested. I can do the remote render per the notebook examples but would like to keep slicer hidden.

Ability to bring up the Slicer application window is a unique advantage compared to other kernels that allow interaction only via the notebook interface. Is Slicer running in the background interferes with your work in some way? Is the problem that there are a few commands that cause Slicer window to be raised on top? We could easily change that, if needed. Or the problem is that the Slicer application window pops up briefly when the kernel starts?

To completely eliminate Slicer from your desktop while it is running is not trivial and would require different solution on each platform (e.g., use virtual desktop and make Slicer start on a hidden one). Probably the easiest way to achieve this would be to change the kernelspec file so that it does not start a locally installed Slicer but it in a docker container.

**Comment by marcmorcos** [comment]
Thank you so much for the reply.

I am not using VS Code. Just the jupyter notebook.

I can live with the app open in the background, just wondering as I was looking to run Slicer w/ Voila and wanted to reduce desktop cluster.

**Comment by lassoan** [comment]
> I am not using VS Code. Just the jupyter notebook.

If I start JupyterLab by clicking on "Start Jupyter server" button then one Slicer kernel is started for each opened notebook, which is justified. Do you see a different behavior? I haven't tried Voila, it may be possible that it launches some extra kernels.

> I can live with the app open in the background, just wondering as I was looking to run Slicer w/ Voila and wanted to reduce desktop cluster.

Slicer should automatically minimize itself after it starts as a kernel, so it should only show up in the taskbar but not on the desktop. If you want to prevent the Slicer from appearing on the task bar then you could use docker, but if you can live with having Slicer appearing in the taskbar then it may not worth spending time with setting up a container.

**Comment by marcmorcos** [comment]
You are correct. Regarding each notebook starting a slicer instance. I didn't realize that Jupyter Lab turns on the kernel for multiple notebooks even though they were previously shutdown.

Thank you!
